# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Build_Backend
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: Dotnet Install
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - task: MSBuild@1
      inputs:
        solution: 'ConferencePlanner\FrontEnd\FrontEnd.csproj'
        platform: 'Any CPU'
        configuration: 'Release'
    - task: MSBuild@1
      inputs:
        solution: 'ConferencePlanner\BackEnd\BackEnd.csproj'
        platform: 'Any CPU'
        configuration: 'Release'
    - task: MSBuild@1
      inputs:
        solution: 'ConferencePlanner\ConferenceDTO\ConferenceDTO.csproj'
        platform: 'Any CPU'
        configuration: 'Release'

#  - job: Build_Frontend
#    pool:
#    steps:
#    - task: NodeTool@0
#      displayName: Node js Install
#      inputs:
#        versionSource: 'spec'
#        versionSpec: '14.x'
#    - task: Npm@1
#      displayName: Install Npm
#      inputs:
#        command: 'install'
#        workingDir: ''
#   - task: Npm@1
#      displayName: Npm run and build
#      inputs:
#        command: 'custom'
#        workingDir: ''
#        customCommand: 'run build'
