# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Build_Backend
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: Install Sdk
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - task: DotNetCoreCLI@2
      displayName: Frontend build
      inputs:
        command: 'build'
        projects: 'src/ConferencePlanner/FrontEnd/FrontEnd.csproj'
    - task: DotNetCoreCLI@2
      displayName: Bakend Build
      inputs:
        command: 'build'
        projects: 'src/ConferencePlanner/BackEnd/BackEnd.csproj'
    - task: DotNetCoreCLI@2
      displayName: ConferenceDTO build
      inputs:
        command: 'build'
        projects: 'src/ConferencePlanner/ConferenceDTO/ConferenceDTO.csproj'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\src\ConferencePlanner\FrontEnd\bin\Debug\net6.0'
        ArtifactName: 'Frontend'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\src\ConferencePlanner\BackEnd\bin\Debug\net6.0'
        ArtifactName: 'Backend'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\src\ConferencePlanner\ConferenceDTO\bin\Debug\net6.0'
        ArtifactName: 'ConferenceDTO'
        publishLocation: 'Container'
    - task: DownloadBuildArtifacts@1
      displayName: download backend artifact
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'backend'
        downloadPath: '$(System.ArtifactsDirectory)'